# Copyright (c) 2024 Bima Kharisma Wicaksana
# ArgoCD Server Parameters Patch
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Run server insecure (TLS termination at ingress)
  server.insecure: "true"

  # Disable TLS for repo server
  reposerver.disable.tls: "true"

  # Application controller settings
  controller.status.processors: "20"
  controller.operation.processors: "10"
  controller.self.heal.timeout.seconds: "5"

  # Server settings
  server.staticassets: /shared/app
  server.rootpath: ""
