# Copyright (c) 2024 Bima Kharisma Wicaksana
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - require-labels.yaml
  - block-privileged.yaml
  - require-resources.yaml
  - allowed-repos.yaml
  - require-probes.yaml
