# Copyright (c) 2024 Bima Kharisma Wicaksana
# Cost Monitoring Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: cost-monitoring
  labels:
    app.kubernetes.io/name: cost-monitoring
    app.kubernetes.io/component: observability
