# Copyright (c) 2024 Bima Kharisma Wicaksana
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

resources:
  - namespace.yaml
  - gatekeeper.yaml
  - config.yaml
