# Copyright (c) 2024 Bima Kharisma Wicaksana
# Example: Docker Registry credentials SealedSecret
#
# To create from actual credentials:
#
# kubectl create secret docker-registry regcred \
#   --docker-server=asia-southeast1-docker.pkg.dev \
#   --docker-username=_json_key \
#   --docker-password="$(cat service-account-key.json)" \
#   --docker-email=sa@project.iam.gserviceaccount.com \
#   --dry-run=client -o yaml | kubeseal --format yaml > docker-registry-secret.yaml
#
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # PLACEHOLDER - replace with actual kubeseal output
    .dockerconfigjson: AgBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...
  template:
    metadata:
      name: regcred
      namespace: default
      labels:
        app.kubernetes.io/name: registry-credentials
    type: kubernetes.io/dockerconfigjson
